import Head from "next/head";
// import Image from "next/image"; // Commenting out as images are removed in this basic version
import { Geist, Geist_Mono } from "next/font/google";
import { useEffect } from "react"; // useState removed, useEffect kept for setting dark class
// styles import removed

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  // darkMode state and toggle function removed

  useEffect(() => {
    // Always apply dark mode on component mount
    document.documentElement.classList.add("dark");
    // Optional: cleanup function to remove the class if the component unmounts,
    // though for a top-level page, this might not be strictly necessary.
    return () => {
      document.documentElement.classList.remove("dark");
    };
  }, []); // Empty dependency array ensures this runs only once on mount

  return (
    <>
      <Head>
        <title>Tailwind Next App - Dark Mode</title> {/* Updated title */}
        <meta
          name="description"
          content="Generated by create next app with Tailwind - Dark Mode"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Dark mode classes will now always apply due to 'dark' class on html */}
      <div
        className={`min-h-screen flex flex-col items-center justify-center bg-gray-100 dark:bg-gray-900 ${geistSans.variable} ${geistMono.variable} font-sans transition-colors duration-300`}
      >
        {/* Toggle button removed */}
        <main className="p-10 bg-white dark:bg-gray-800 rounded-lg shadow-xl text-center transition-colors duration-300">
          <h1 className="text-4xl font-bold text-blue-600 dark:text-blue-400 mb-4 transition-colors duration-300">
            Welcome to Tailwind Next.js!
          </h1>
          <p className="text-gray-700 dark:text-gray-300 text-lg transition-colors duration-300">
            This is a simple starter page using Tailwind CSS (Dark Mode by
            default).
          </p>
          <p className="mt-6 text-sm text-gray-500 dark:text-gray-400 transition-colors duration-300">
            Get started by editing <code>pages/index.tsx</code>
          </p>
        </main>
      </div>
    </>
  );
}
